export const photos = [
  { id: 22, image: "/Photos/The glowing art deco figures — Grid Hero.jpg", story: "", tags: ["Theatre", "Architecture", "Odeon", "Edit"], group: "Odeon 70mm", isMain: true},
  { id: 23, image: "/Photos/The wider architectural view — Extra Frame.jpg", story: "", tags: ["Theatre", "Architecture", "Odeon", "Edit"], group: "Odeon 70mm", isMain: false},
  { id: 20, image: "/Photos/Moody Aviation Shot 2.jpg", story: "", tags: ["Plane", "Aviation", "max", "Edit"], group: "Moody aviation", isMain: true},
  { id: 21, image: "/Photos/Moody Aviation Shot 1.jpg", story: "", tags: ["Plane", "Aviation", "max", "Edit"], group: "Moody aviation", isMain: false},
  { id: 12, image: "/Photos/Heidi-Love-Baking.jpg", story: "", tags: ["Richmond", "Street", "Bakery", "Edit"], group: "heidi", isMain: true},
  { id: 13, image: "/Photos/Heidi-Love-Baking org.jpg", story: "", tags: ["Richmond", "Street", "Bakery", "Raw"], group: "heidi", isMain: false},
  { id: 17, image: "/Photos/Morning Walk.jpg", story: "", tags: ["Richmond", "Morning walk", "park", "edit"], group: "Morning Walk", isMain: true},
  { id: 18, image: "/Photos/Man bw trees 1.jpg", story: "", tags: ["Richmond", "Morning walk", "park", "raw"], group: "Morning Walk", isMain: false },
  { id: 19, image: "/Photos/Man bw trees.jpg", story: "", tags: ["Richmond", "Morning walk", "park"], group: "Morning Walk", isMain: false },
  { id: 5, image: "/Photos/Full Rainbow.jpg", story: "", tags: ["Rainbow", "Weather"], group: "rainbow", isMain: false },
  { id: 7, image: "/Photos/Rainbow Arc.jpg", story: "", tags: ["Rainbow", "Weather"], group: "rainbow", isMain: true },
  { id: 1, image: "/Photos/Riverside.jpg", story: "", tags: ["Riverside", "Kingston"], group: "", isMain: true },
  { id: 2, image: "/Photos/Plane.jpg", story: "", tags: ["Sky", "Plane"], group: "", isMain: true },
  { id: 3, image: "/Photos/Plane in the Sky.jpg", story: "", tags: ["Plane", "Sky"], group: "", isMain: true },
  { id: 4, image: "/Photos/Autumn Evening.jpg", story: "", tags: ["Autumn", "Evening"], group: "", isMain: true },
  { id: 6, image: "/Photos/Empty street.jpg", story: "", tags: ["Street", "Weather"], group: "", isMain: true },
  { id: 8, image: "/Photos/Sunny Evening.jpg", story: "", tags: ["Evening"], group: "", isMain: true },
  { id: 9, image: "/Photos/Telephone Booth.jpg", story: "", tags: ["Telephone Booth", "Street", "Evening"], group: "", isMain: true },
  { id: 10, image: "/Photos/Terminal 5.jpg", story: "", tags: ["Terminal", "People"], group: "", isMain: true },
  { id: 11, image: "/Photos/Afadena.jpg", story: "", tags: ["Food", "Afadena"], group: "", isMain: true },
  { id: 24, image: "/Photos/[Wildlife_Deer_Nature_Richmond]_Deer_Capture_Different.jpg", story: "", tags: ["Wildlife", "Deer", "Nature", "Richmond"], group: "Deer Capture", isMain: false },
  { id: 25, image: "/Photos/[Wildlife_Deer_Nature_Richmond]_Deer_Capture_Hero.jpg", story: "", tags: ["Wildlife", "Deer", "Nature", "Richmond"], group: "Deer Capture", isMain: true }
];
